'use strict';
const KEY='cartoveille_free_v1';
let db=load();
function load(){try{const d=JSON.parse(localStorage.getItem(KEY));if(d&&Array.isArray(d.companies)&&Array.isArray(d.events)&&Array.isArray(d.prices))return {...d,intel:Array.isArray(d.intel)?d.intel:[]}}catch(e){}return {companies:[],events:[],prices:[],intel:[]}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(db))}catch(e){alert('Stockage indisponible ou saturé. Exportez vos données.');return}render()}
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random();
const today=()=>new Date().toLocaleDateString('en-CA');
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2800)}
function show(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===view));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));
document.querySelectorAll('[data-goto]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.goto)));
function field(form){return Object.fromEntries(new FormData(form).entries())}
function external(url,label){try{let u=new URL(url);if(!['https:','http:'].includes(u.protocol))return '';return `<a href="${esc(u.href)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`}catch(e){return ''}}
function fmt(n){return Number(n).toLocaleString('fr-FR',{maximumFractionDigits:4})}
function empty(msg){return `<div class="empty">${esc(msg)}</div>`}
function del(kind,id){if(!confirm('Supprimer définitivement cet élément ?'))return;db[kind]=db[kind].filter(x=>x.id!==id);save();toast('Élément supprimé')}
window.removeItem=del;
$('companyForm').addEventListener('submit',e=>{e.preventDefault();let x=field(e.target);x.name=x.name.trim();if(!x.name)return;db.companies.unshift({...x,id:uid()});e.target.reset();save();toast('Entreprise enregistrée')});
$('eventForm').addEventListener('submit',e=>{e.preventDefault();let x=field(e.target);if(!x.title.trim())return;db.events.unshift({...x,id:uid()});e.target.reset();e.target.elements.date.value=today();save();toast('Information enregistrée')});
$('intelForm').addEventListener('submit',e=>{e.preventDefault();const x=field(e.target);if(!x.companyId||!x.metric.trim()||!x.value.trim()||!x.source.trim())return;db.intel.unshift({...x,id:uid(),recordedAt:new Date().toISOString()});e.target.reset();e.target.elements.published.value=today();save();toast('Information ajoutée à la fiche concurrent')});
$('priceForm').addEventListener('submit',e=>{e.preventDefault();let x=field(e.target);if(!x.product.trim()||+x.quantity<=0||+x.unitPrice<=0)return;db.prices.unshift({...x,id:uid()});e.target.reset();e.target.elements.date.value=today();save();toast('Prix enregistré')});
['companyFilter','eventFilter','priceFilter','regionFilter','intelFilter'].forEach(id=>$(id).addEventListener('input',render));
function render(){
$('countCompanies').textContent=db.companies.length;$('countEvents').textContent=db.events.length;$('countPrices').textContent=db.prices.length;$('countHigh').textContent=db.events.filter(x=>x.importance!=='Normale').length;
$('intelCompany').innerHTML='<option value="">Sélectionner une entreprise</option>'+db.companies.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');
$('eventCompany').innerHTML='<option value="">Non attribuée</option>'+db.companies.map(x=>`<option value="${esc(x.name)}">${esc(x.name)}</option>`).join('');
let evs=[...db.events].sort((a,b)=>(b.date||'').localeCompare(a.date||''));
function eventHtml(x){return `<div class="entry"><div class="row"><h3>${esc(x.title)}</h3><span class="tag ${x.importance==='Critique'?'critical':x.importance==='Élevée'?'high':''}">${esc(x.importance)}</span></div><div class="meta">${esc(x.date)} · ${esc(x.category)}${x.company?' · '+esc(x.company):''}${x.source?' · '+esc(x.source):''}</div>${x.summary?`<p>${esc(x.summary)}</p>`:''}<div class="row">${x.url?external(x.url,'Lire la source'):'<span class="meta">Source URL non renseignée</span>'}<button class="delete" onclick="removeItem('events','${esc(x.id)}')">Supprimer</button></div></div>`}
$('homeEvents').innerHTML=evs.slice(0,4).map(eventHtml).join('')||empty('Aucune actualité enregistrée.');
$('eventsList').innerHTML=evs.filter(x=>JSON.stringify(x).toLowerCase().includes($('eventFilter').value.toLowerCase())).map(eventHtml).join('')||empty('Aucune information correspondante.');
let companies=db.companies.filter(x=>JSON.stringify(x).toLowerCase().includes($('companyFilter').value.toLowerCase()));
$('companiesList').innerHTML=companies.map(x=>`<div class="entry"><div class="row"><h3>${esc(x.name)}</h3><button class="delete" onclick="removeItem('companies','${esc(x.id)}')">Supprimer</button></div><div class="meta">${esc([x.activity,x.city,x.department,x.region].filter(Boolean).join(' · '))}</div>${x.notes?`<p>${esc(x.notes)}</p>`:''}${x.website?external(x.website,'Site de l’entreprise'):''}</div>`).join('')||empty('Aucune entreprise correspondante.');
let term=$('intelFilter').value.toLocaleLowerCase('fr');let related=db.companies.filter(c=>(c.name+' '+c.city+' '+c.region+' '+(db.intel||[]).filter(i=>i.companyId===c.id).map(i=>JSON.stringify(i)).join(' ')).toLocaleLowerCase('fr').includes(term));
$('intelList').innerHTML=related.map(c=>{let records=(db.intel||[]).filter(i=>i.companyId===c.id).sort((a,b)=>(b.published||'').localeCompare(a.published||''));let groups=['Financier','Commercial','Industriel','Gouvernance','Autre'].map(domain=>{let items=records.filter(i=>i.domain===domain);return items.length?`<h4>${domain} (${items.length})</h4>`+items.map(i=>`<div class="entry"><div class="row"><strong>${esc(i.metric)} : ${esc(i.value)}</strong><span class="tag">${esc(i.status)}</span></div><div class="meta">${esc([i.site,i.period,i.published,i.source].filter(Boolean).join(' · '))}</div>${i.notes?`<p>${esc(i.notes)}</p>`:''}<div class="row">${i.url?external(i.url,'Consulter la source'):'<span class="meta">URL non renseignée</span>'}<button class="delete" onclick="removeItem('intel','${esc(i.id)}')">Supprimer</button></div></div>`).join(''):''}).join('');let timeline=db.events.filter(e=>e.company===c.name).sort((a,b)=>(b.date||'').localeCompare(a.date||''));return `<details class="entry"><summary><b>${esc(c.name)}</b> — ${esc([c.city,c.region].filter(Boolean).join(' · '))} <span class="tag">${records.length} information(s)</span></summary><p>${c.website?external(c.website,'Site officiel'):''} ${c.notes?esc(c.notes):''}</p>${groups||empty('Aucune information sourcée. Utilisez le formulaire ci-dessus.')}<h4>Chronologie (${timeline.length})</h4>${timeline.map(e=>`<div class="meta">${esc(e.date)} · ${esc(e.title)} ${e.url?external(e.url,'Source'):''}</div>`).join('')||'<p class="muted">Aucun événement lié à cette entreprise.</p>'}</details>`}).join('')||empty('Aucune fiche correspondante. Ajoutez une entreprise puis ses informations sourcées.');
let regions=[...new Set(db.companies.map(x=>x.region).filter(Boolean))].sort();let selected=$('regionFilter').value;$('regionFilter').innerHTML='<option value="">Toutes les régions</option>'+regions.map(r=>`<option value="${esc(r)}" ${selected===r?'selected':''}>${esc(r)}</option>`).join('');
$('geoList').innerHTML=db.companies.filter(x=>!selected||x.region===selected).map(x=>{let lat=Number(x.lat),lng=Number(x.lng),valid=x.lat!==''&&x.lng!==''&&Number.isFinite(lat)&&Number.isFinite(lng);return `<div class="entry"><h3>${esc(x.name)}</h3><div class="meta">${esc([x.city,x.department,x.region].filter(Boolean).join(' · '))}</div>${valid?external(`https://www.openstreetmap.org/?mlat=${lat}&mlon=${lng}#map=12/${lat}/${lng}`,'Voir sur OpenStreetMap'):'<span class="meta">Coordonnées non renseignées</span>'}</div>`}).join('')||empty('Aucun site dans cette région.');
$('pricesList').innerHTML=db.prices.filter(x=>JSON.stringify(x).toLowerCase().includes($('priceFilter').value.toLowerCase())).map(x=>`<div class="entry"><div class="row"><h3>${esc(x.product)}</h3><span class="tag">${fmt(x.unitPrice)} € HT / p.</span></div><div class="meta">${esc(x.competitor)} · ${fmt(x.quantity)} pièces · ${esc(x.date)} · ${esc(x.type)} · ${esc(x.confidence)}</div>${x.specs?`<p>${esc(x.specs)}</p>`:''}<div class="row"><span class="meta">${esc(x.source||'Source non renseignée')}</span><button class="delete" onclick="removeItem('prices','${esc(x.id)}')">Supprimer</button></div></div>`).join('')||empty('Aucune référence de prix correspondante.');
}
$('estimateForm').addEventListener('submit',e=>{e.preventDefault();let product=$('estimateProduct').value.trim().toLocaleLowerCase('fr'),q=+$('estimateQuantity').value;let matches=db.prices.filter(x=>x.product.trim().toLocaleLowerCase('fr')===product&&x.confidence==='Documenté'&&+x.quantity>0&&+x.unitPrice>0);if(!matches.length){$('estimateResult').innerHTML='<b>Aucun comparable documenté.</b><p>Ajoutez des prix de la même référence produit dans « Prix marché ». Aucune estimation n’est produite.</p>';return}let close=matches.filter(x=>+x.quantity/q>=.5&&+x.quantity/q<=2);let used=close.length?close:matches;let vals=used.map(x=>+x.unitPrice),min=Math.min(...vals),max=Math.max(...vals),avg=vals.reduce((a,b)=>a+b,0)/vals.length;$('estimateResult').innerHTML=`<strong>${fmt(avg)} € HT / pièce</strong><p>Fourchette observée : <b>${fmt(min)} – ${fmt(max)} €</b> · ${used.length} comparable(s) documenté(s)</p><p class="meta">${close.length?'Quantités comprises entre 50 % et 200 % du volume demandé.':'Aucun volume proche : références de quantités différentes, comparaison fragile.'} Moyenne simple, non corrigée des différences techniques, des conditions commerciales ni des dates. Vérifiez les spécifications avant toute décision. Ce résultat n'est pas une recommandation de prix de vente.</p>`});
function exportDb(){let blob=new Blob([JSON.stringify({format:'CartoVeille-Free-v1',exportedAt:new Date().toISOString(),...db},null,2)],{type:'application/json'});let u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='CartoVeille_sauvegarde_'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),2000);toast('Sauvegarde téléchargée')}
$('exportTop').addEventListener('click',exportDb);$('exportBtn').addEventListener('click',exportDb);
$('importFile').addEventListener('change',async e=>{let file=e.target.files[0];if(!file)return;try{let d=JSON.parse(await file.text());if(!['companies','events','prices'].every(k=>Array.isArray(d[k])))throw Error('Format incompatible');if(!confirm('Remplacer toutes les données locales par celles de cette sauvegarde ?'))return;db={companies:d.companies,events:d.events,prices:d.prices,intel:Array.isArray(d.intel)?d.intel:[]};save();toast('Sauvegarde importée')}catch(err){alert('Import impossible : '+err.message)}finally{e.target.value=''}});
$('clearBtn').addEventListener('click',()=>{if(confirm('Effacer toutes les données de cet appareil ? Cette action est irréversible sans sauvegarde.')){db={companies:[],events:[],prices:[],intel:[]};save();toast('Données effacées')}});
for(let form of ['eventForm','priceForm','intelForm'])$(form).elements.date.value=today();
if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
render();
